name: CI

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-22.04, macos-13, macos-latest, windows-11-arm]
        os: [windows-latest, ubuntu-22.04, macos-13, macos-latest]
        include:
          - os: windows-latest
            build: CiaPPo-Windows.exe
          - os: ubuntu-22.04
            build: CiaPPo-Linux
          - os: macos-13
            build: CiaPPo-macOS-Intel
          - os: macos-latest
            build: CiaPPo-macOS-Apple_Silicon
          # - os: windows-11-arm
          #   build: BHYG-Windows-arm.exe
    runs-on: ${{ matrix.os }}
    env:
      version: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Binary
        run: pyinstaller main.spec

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: dist/${{ github.ref_name }}-${{ matrix.build }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/${{ github.ref_name }}-${{ matrix.build }}
